-- =========================================================================
-- 0070 — analytics_events
--
-- Tabella append-only allineata a docs/ANALYTICS_INGEST_CONTRACT.md
-- e al payload di web/lib/analytics-ingest.ts.
--
-- Decisioni:
--   • id bigint generated by default as identity (alta cardinalità, append-only).
--   • client_event_id text nullable, UNIQUE (parziale) → idempotenza su retry,
--     ack puntuale (vedi accepted_event_ids nel contratto).
--   • event_type vincolato al set v1 congelato in PRE_WIRING_CONCEPT §B.
--   • campaign_id FK → SET NULL (gli eventi sopravvivono se la campagna è eliminata,
--     storico denormalizzato già su utm_* + cid).
--   • UPDATE non previsto da v1 (modello append-only); non si traccia updated_at.
--   • received_at = timestamp lato server (utile per debug clock skew).
--
-- Nessuna FK verso candidates: collegamento debole via session_id /
-- funnel_attempt_id (PRE_WIRING_CONCEPT §"ERD minimo" Note).
-- =========================================================================

create table if not exists public.analytics_events (
  id                 bigint generated by default as identity primary key,
  client_event_id    text,
  occurred_at        timestamptz not null,
  received_at        timestamptz not null default now(),
  session_id         text not null,
  funnel_attempt_id  text,
  event_type         text not null,

  -- attribution denormalizzata (storica fedele al click)
  campaign_id        uuid
                       references public.campaigns (id) on delete set null,
  cid                text,
  utm_source         text,
  utm_medium         text,
  utm_campaign       text,
  utm_term           text,
  utm_content        text,

  -- dettagli "una sola semanticamente"
  cta_key            text,
  form_step_index    smallint,
  form_field_key     text,
  city_slug          text,

  constraint analytics_events_event_type_check
    check (event_type in (
      'page_view',
      'cta_click',
      'careers_form_open',
      'careers_step_view',
      'careers_abandon',
      'careers_submit'
    )),
  constraint analytics_events_session_id_length_check
    check (char_length(btrim(session_id)) between 1 and 128),
  constraint analytics_events_form_step_index_check
    check (form_step_index is null or form_step_index between 0 and 32),
  -- Vincolo concettuale: cta_click richiede cta_key (PRE_WIRING_CONCEPT §B).
  constraint analytics_events_cta_click_requires_cta_key_check
    check (event_type <> 'cta_click' or cta_key is not null),
  -- careers_step_view e careers_abandon richiedono lo step index.
  constraint analytics_events_step_view_requires_step_index_check
    check (event_type <> 'careers_step_view' or form_step_index is not null),
  constraint analytics_events_abandon_requires_step_index_check
    check (event_type <> 'careers_abandon' or form_step_index is not null)
);

comment on table public.analytics_events is
  'Eventi funnel sito (append-only). Allineato a ANALYTICS_INGEST_CONTRACT.md v1.';
comment on column public.analytics_events.client_event_id is
  'UUID generato dal client per idempotenza/ack (UNIQUE quando presente).';
comment on column public.analytics_events.received_at is
  'Timestamp lato server (debug clock skew); occurred_at resta il timestamp evento.';
comment on column public.analytics_events.cid is
  'Token campagna pubblico ricevuto dal link; usato per risolvere campaign_id.';
comment on column public.analytics_events.city_slug is
  'Sede selezionata nel funnel careers (dim. denormalizzata; in candidates resta city_id).';

-- Idempotenza retry: client_event_id univoco quando presente.
create unique index if not exists analytics_events_client_event_id_uidx
  on public.analytics_events (client_event_id)
  where client_event_id is not null;

-- Indici per query KPI (CAMPAIGNS_CONTRACT §5).
create index if not exists analytics_events_occurred_at_idx
  on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_event_type_occurred_idx
  on public.analytics_events (event_type, occurred_at desc);
create index if not exists analytics_events_campaign_occurred_idx
  on public.analytics_events (campaign_id, occurred_at desc)
  where campaign_id is not null;
create index if not exists analytics_events_cid_occurred_idx
  on public.analytics_events (cid, occurred_at desc)
  where cid is not null;
create index if not exists analytics_events_session_id_idx
  on public.analytics_events (session_id);
create index if not exists analytics_events_funnel_attempt_idx
  on public.analytics_events (funnel_attempt_id)
  where funnel_attempt_id is not null;
create index if not exists analytics_events_city_slug_submit_idx
  on public.analytics_events (city_slug)
  where event_type = 'careers_submit' and city_slug is not null;
